@startuml
'https://plantuml.com/sequence-diagram
skinparam ParticipantPadding 15
hide footbox

Actor User
participant ":Medicine" as Medicine
participant "medicineList:ArrayList<Medicine>" as medicineList
participant ":MedicineStorage" as medicineStorage
User-> Medicine: deleteMedicine(medicineName)
activate Medicine

Medicine -> medicineList : removeIf(predicate)
activate medicineList
loop for all medicine in\n medicineList
medicineList -> Medicine : getMedicineName()
    activate Medicine
    Medicine --> medicineList : medicineName
    deactivate Medicine


alt equalsIgnoreCase\n(medicineName)
medicineList -> medicineList : remove(medicineName)
activate medicineList
medicineList --> medicineList
deactivate medicineList
medicineList --> Medicine: removed = true
else !equals\nIgnore\nCase\n(medicine\nName)
medicineList --> Medicine: removed = false
deactivate medicineList
end
end

alt removed
Medicine -> medicineStorage : overwriteSaveFile(medicineList)
activate medicineStorage
medicineStorage --> Medicine
deactivate medicineStorage
Medicine --> User : System.out.println()

else !removed

Medicine --> User : NurseSchedException
deactivate Medicine
end

@enduml