@startuml

hide footbox
actor User
participant ":Command" as Command
participant ":Parser" as Parser
participant ":TaskParser" as TaskParser
participant ":Task" as Task
participant "taskList:ArrayList" as taskList

User -> Command : add a task
activate Command

Command -> Parser : extractType(user input)
activate Parser

Parser --> Command : task type
deactivate Parser

Command -> TaskParser : extractInputs(user input parameters)
activate TaskParser

TaskParser --> Command : TaskParser object with parameters
deactivate TaskParser

Command-> Task : addTask(task details)
activate Task

Task -> taskList : add()
activate taskList

taskList -> Task : create new task
activate Task

Task --> taskList : new task
deactivate Task

taskList --> Task
deactivate taskList

Task --> Command : task added
deactivate Task
Command --> User
deactivate Command
deactivate Task

@enduml