@startuml

hide circle
skinparam classAttributeIconSize 0

package "Patient Information" {
  class Patient {
    -id: String
    -name: String
    -age: String
    -gender: String
    -contact: String
    -notes: String
    # {static} patientsList: ArrayList<Patient>
    +Patient(id, name, age, gender, contact, notes)
    + {static} addPatient(Patient)
    +{static}removePatient(String)
    +{static}listPatientInformation()
    +{static}editPatientDetails(id, name, age, gender, contact, notes)
    +{static}printProfileWithID(String)
  }

  class MedicalTest {
    -patientId: String
    -testName: String
    -result: String
    #{static}medicalTestList: ArrayList<MedicalTest>
    +MedicalTest(patientId, testName, result)
    +{static}addMedicalTest(MedicalTest)
    +{static}removeTestsForPatient(String)
    +{static}listTestsForPatient(String)
  }
}

package "Command Process" {
  class Command {
    +executeCommands(boolean, Scanner, Ui)
  }

  class PatientParser {
    -command: String
    -id: String
    -name: String
    -age: String
    -gender: String
    -contact: String
    -notes: String
    +PatientParser(command, id, name, age, gender, contact, notes)
    +{static}extractInputs(String): PatientParser
    -{static}validateID(String)

  }
}

Command .right.> PatientParser : 1. parses input >
Command ..> Patient : 2. executes >

Patient *-right- "0..*" MedicalTest : contains >


@enduml