@startuml

hide circle
skinparam classAttributeIconSize 0

package "Patient Information" {
  class Patient {
    -id: String
    -name: String
    -age: String
    -gender: String
    -contact: String
    -notes: String
    # {static} patientsList: ArrayList<Patient>
    +Patient(id, name, age, gender, contact, notes)
    +addPatient(Patient)
    +removePatient(String)
    +listPatientInformation()
    +editPatientDetails(id, name, age, gender, contact, notes)
    +printProfileWithID(String)
  }

  class MedicalTest {
    -patientId: String
    -testName: String
    -result: String
    #{static}medicalTestList: ArrayList<MedicalTest>
    +MedicalTest(patientId, testName, result)
    +addMedicalTest(MedicalTest)
    +removeTestsForPatient(String)
    +listTestsForPatient(String)
  }
}

package "Command Process" {
  class Command {
    +executeCommands(boolean, Scanner, Ui)
  }

  class PatientParser {
    -command: String
    -id: String
    -name: String
    -age: String
    -gender: String
    -contact: String
    -notes: String
    +PatientParser(command, id, name, age, gender, contact, notes)
    +extractInputs(String): PatientParser
    +validateID(String)
  }
}

Command .right.> PatientParser : 1. parses input >
Command ..> Patient : 2. executes >

Patient *-right- "0..*" MedicalTest : contains >


@enduml