@startuml

hide footbox
actor User
participant ":Command" as Command
participant ":Parser" as Parser
participant ":ApptParser" as ApptParser
participant ":Appointment" as Appt
participant ":AppointmentStorage" as Storage

User -> Command : appt add id/1234 s/13:00 e/14:00 d/2025-12-12 \nim/3 n/Needs a wheelchair"
activate Command
  Command -> Parser : extractType(line)

  activate Parser
    Parser --> Command : Return "appt"
  deactivate Parser

  Command -> ApptParser : extractInputs(line)

  activate ApptParser

    ApptParser --> Command : ApptParser \nobject with parameters
  deactivate ApptParser

  Command -> Appt : addAppt(id="1234", startTime=13:00, endTime=14:00, date=2025-12-12, \nim=3, notes="Needs a wheelchair")

  activate Appt

    Appt -> Appt: findApptClashes(startTime=13:00,endTime=14:00,date=2025-12-12)
    activate Appt
        Appt --> Appt: Possible Appointment Clashes
    deactivate Appt



    alt Appointment clashes exists
        Appt -> Command : Appointment \nnot added
    else No appointment clashes

        Appt -> Appt: checkApptDateTime(date,startTime,endTime)
        activate Appt
        deactivate Appt

        Appt -> Storage : appendToFile(Appt)
        activate Storage
            Storage --> Appt : File saved
        deactivate Storage

        Appt --> Command: Appointment \nadded
        deactivate Appt
    end




  Command --> User
deactivate Command
@enduml