@startuml

hide footbox
actor User
participant ":Command" as Command
participant ":Parser" as Parser
participant ":ApptParser" as ApptParser
participant ":Appointment" as Appt
participant "apptList:ArrayList" as ApptList
participant ":AppointmentStorage" as ApptStorage

User -> Command : appt sort by/ importance
activate Command

Command -> Parser : extractType(line)
activate Parser

Parser --> Command : Return "appt"
deactivate Parser

Command -> ApptParser : extractInputs(line)
activate ApptParser
ApptParser --> Command : ApptParser \nobject with \nparameters
deactivate ApptParser

opt sortBy.equals("importance")
    Command-> Appt : sortByImportance()
    activate Appt

    Appt -> ApptList : isEmpty()
    activate ApptList

    ApptList --> Appt : True/False


    alt apptList is empty
        Appt --> Command : List is empty. \nNothing to sort.
    else apptList is not empty
        Appt -> ApptList : sort(Comparator)
        ApptList --> Appt
        deactivate ApptList



    Appt -> ApptStorage : overwriteSaveFile()
    activate ApptStorage

    ApptStorage --> Appt : File saved
    deactivate ApptStorage



    Appt --> Command : List sorted successfully
    deactivate Appt
    Command --> User
    deactivate Command
    end


end





@enduml